<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Services Language Lines
    |--------------------------------------------------------------------------
    |
    |
    */

    'Services' => 'Services',
    'Legal Advisory & support' => 'Legal Advisory & support',
    'Experts Directory' => 'Experts Directory',
    'Financial Management Support' => 'Financial Management Support',
    'CSO Directories' => 'CSO Directories',
    'Research and Documentation' => 'Research and Documentation',
    'Capacity Development' => 'Capacity Development',
    'CSO Media Centre' => 'CSO Media Centre',
    'CSO Annual Conference' => 'CSO Annual Conference',
    'Public Policy Watch' => 'Public Policy Watch',
    'Community Dialogue' => 'Community Dialogue',
    'ICT4D and Biz Incubation Hub' => 'ICT4D and Biz Incubation Hub',
    'Small Grant Scheme' => 'Small Grant Scheme',
    'Meals' => 'Meals',
    'Lodging Facilities' => 'Lodging Facilities',
    'Children Parliament' => 'Children Parliament',
    'Human Resource directory' => 'Human Resource directory',
    'The CSO Information and Data Centre (physical/online)' => 'The CSO Information and Data Centre (physical/online)',
    'Continuous Capacity Building' => 'Continuous Capacity Building',
    'Strategic networking & twining' => 'Strategic networking & twining',
    'Advocacy and lobby for Donor Process streamlining' => 'Advocacy and lobby for Donor Process streamlining',
    'Framework for Consultation and dialogue (physical/online)' => 'Framework for Consultation and dialogue (physical/online)',
    'Establish a very detailed directory of CSO in Cameroon ranked on the basis of an institutional/operational micro assessment conducted on each organization using a mutually agreed assessment tool. The center then works to accompany the CSO to improve their institutional and operational capacities and hence migrate from one category to the other.  The directory is made available online/offline and updated yearly by the Data department of the center' => 'Establish a very detailed directory of CSO in Cameroon ranked on the basis of an institutional/operational micro assessment conducted on each organization using a mutually agreed assessment tool. The center then works to accompany the CSO to improve their institutional and operational capacities and hence migrate from one category to the other.  The directory is made available online/offline and updated yearly by the Data department of the center',
    'A directory of experts in different domains is established and made available online/offline at the center to provide timely and quality technical support to the civil society.  The directory is updated yearly.' => 'A directory of experts in different domains is established and made available online/offline at the center to provide timely and quality technical support to the civil society.  The directory is updated yearly.',
    'To address the human resource challenges faced by the civil society resulting from high staff turnover and low practical skills among graduates, this service of LACSODEC will focus on a structured professional internship for university graduates aimed at preparing them to the labor pool from where CSO can draw quality human capital. This directory is available offline/online and updated regularly' => 'To address the human resource challenges faced by the civil society resulting from high staff turnover and low practical skills among graduates, this service of LACSODEC will focus on a structured professional internship for university graduates aimed at preparing them to the labor pool from where CSO can draw quality human capital. This directory is available offline/online and updated regularly',
    'Accommodate at the center a qualified audit department charged with the development of tools and training modules based on the standard accounting standards (OHADA) and use the same to train and accompany civil society and youth’s startups to establish compliant financial management systems. The department will therefore conduct yearly audits and certify the accounts of participating CSO and thereby increase their eligibility to access resources at national, regional and international levels.' => 'Accommodate at the center a qualified audit department charged with the development of tools and training modules based on the standard accounting standards (OHADA) and use the same to train and accompany civil society and youth’s startups to establish compliant financial management systems. The department will therefore conduct yearly audits and certify the accounts of participating CSO and thereby increase their eligibility to access resources at national, regional and international levels.',
    'Accommodate a legal advisory department charged with the responsibility to research, analyze, simplify, share and train CSO on available legal frameworks (National, regional and international) guiding their general operations as well as sector-specific reference source documents. The Legal department also has the responsibility to establish a national and regional referral pathway of legal experts to provide timely legal counsel to CSO as well as trigger the network to protect CSO actors in cases of harassment related to their work.' => 'Accommodate a legal advisory department charged with the responsibility to research, analyze, simplify, share and train CSO on available legal frameworks (National, regional and international) guiding their general operations as well as sector-specific reference source documents. The Legal department also has the responsibility to establish a national and regional referral pathway of legal experts to provide timely legal counsel to CSO as well as trigger the network to protect CSO actors in cases of harassment related to their work.',
    'The information and data center (library/archive) will collect and keep resourceful publications good for CSO reference for knowledge and/or consultation during programs/project formulation. The department conducts ongoing assessments, research and publications that are then used to inform local, national, regional and international policy formulation and for evidence-based advocacy for positive change. The center provides secured data backup service that can be used by CSO to prevent data loss that is frequent among CSOs.' => 'The information and data center (library/archive) will collect and keep resourceful publications good for CSO reference for knowledge and/or consultation during programs/project formulation. The department conducts ongoing assessments, research and publications that are then used to inform local, national, regional and international policy formulation and for evidence-based advocacy for positive change. The center provides secured data backup service that can be used by CSO to prevent data loss that is frequent among CSOs.',
    'A key aspect of the LACSODEC is to develop and deliver content and mentorship in specific areas of institutional and operational capacity of the civil society organizations using a hybrid of physical workshops and high technologies such as video conferencing and distant learning. Peer mentorship will be encouraged and supported to allow best practices to be shared across the civil society via placement programs horizontally and vertically across the nation, continent and globally.' => 'A key aspect of the LACSODEC is to develop and deliver content and mentorship in specific areas of institutional and operational capacity of the civil society organizations using a hybrid of physical workshops and high technologies such as video conferencing and distant learning. Peer mentorship will be encouraged and supported to allow best practices to be shared across the civil society via placement programs horizontally and vertically across the nation, continent and globally.',
    'To meet up with the fast technology world, drawing from the ever-increasing number of youth tech enthusiasts, this department will provide the infrastructure needed to support the development of technologies that respond to the needs of the civil society in particular but also those of businesses, local/national institutions and governments in general. The work of this department will support the digitalization of the LACSODEC as a whole. This service will therefore research, develop and acquire technologies and make these available and accessible to the civil society to improve institutional and operational performance including teleconferencing facilities that can aid holding of meetings and networking remotely and regularly as compared to current cost intensive systems.' => 'To meet up with the fast technology world, drawing from the ever-increasing number of youth tech enthusiasts, this department will provide the infrastructure needed to support the development of technologies that respond to the needs of the civil society in particular but also those of businesses, local/national institutions and governments in general. The work of this department will support the digitalization of the LACSODEC as a whole. This service will therefore research, develop and acquire technologies and make these available and accessible to the civil society to improve institutional and operational performance including teleconferencing facilities that can aid holding of meetings and networking remotely and regularly as compared to current cost intensive systems.',
    'As a means of promoting and testing acquired knowledge and skills, LUKMEF is introducing the LUKMEF small grant program aimed at providing small grants($1000 - $5000) to small and middle incomes organizations to implement impactful institutional strengthening actions and small human development projects in their respective areas of expertise as a way of validating their institutional and operational capacity toward accessing bigger donor funds.' => 'As a means of promoting and testing acquired knowledge and skills, LUKMEF is introducing the LUKMEF small grant program aimed at providing small grants($1000 - $5000) to small and middle incomes organizations to implement impactful institutional strengthening actions and small human development projects in their respective areas of expertise as a way of validating their institutional and operational capacity toward accessing bigger donor funds.',
    'The center will pay particular attention to the Monitoring, Evaluation and Learning system by developing tools, training modules and delivering same to CSO as well accompanying them towards effective use of tools and collection of qualitative and quantitative data that is used to inform their programs/project formulation and evidence-based advocacy for change.' => 'The center will pay particular attention to the Monitoring, Evaluation and Learning system by developing tools, training modules and delivering same to CSO as well accompanying them towards effective use of tools and collection of qualitative and quantitative data that is used to inform their programs/project formulation and evidence-based advocacy for change.',
    'As a strategy to bring visibility and to take its content to beneficiaries in a cost-effective way, the center is designed to harbor a development communication Media center (TV, Radio, Print and online) that has been tested in Buea for the last 3 years to be effective' => 'As a strategy to bring visibility and to take its content to beneficiaries in a cost-effective way, the center is designed to harbor a development communication Media center (TV, Radio, Print and online) that has been tested in Buea for the last 3 years to be effective',
    'Support the yearly organization of a civil society review conference aimed at conducting a global appraisal of the performance of CSO and the operating environment for CSO' => 'Support the yearly organization of a civil society review conference aimed at conducting a global appraisal of the performance of CSO and the operating environment for CSO',
    'While LACSODEC is not a network, the center encourages, facilitates and supports north-south and south-south bilateral and multilateral networking, twining and collaboration between CSOs and relevant national and international agencies likely to add value to CSO institutional and operational capacity.' => 'While LACSODEC is not a network, the center encourages, facilitates and supports north-south and south-south bilateral and multilateral networking, twining and collaboration between CSOs and relevant national and international agencies likely to add value to CSO institutional and operational capacity.',
    'Based on evidence and available accompanying mechanisms, engage with development partners, relevant state agencies and corporate bodies to streamline funding eligibility criteria to accommodate low, middle income and start-up organizations' => 'Based on evidence and available accompanying mechanisms, engage with development partners, relevant state agencies and corporate bodies to streamline funding eligibility criteria to accommodate low, middle income and start-up organizations',
    'Promote public-private sector dialogue and partnerships for local and national development through a hybrid of physical and technologies to bridge the resource gap that limited such processes in the past.' => 'Promote public-private sector dialogue and partnerships for local and national development through a hybrid of physical and technologies to bridge the resource gap that limited such processes in the past.',

];
