<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Services French Language Lines
    |--------------------------------------------------------------------------
    |
    |
    */

    'Services' => 'Services',
    'Legal Advisory & support' => 'Conseil Juridique & Soutien',
    'Experts Directory' => 'Répertoire des experts',
    'Financial Management Support' => 'Soutien à la Gestion Financière',
    'CSO Directories' => 'Annuaires des OSC',
    'Research and Documentation' => 'Recherche et Documentation',
    'Capacity Development' => 'Développement des Capacités',
    'CSO Media Centre' => 'Centre des Médias des OSC',
    'CSO Annual Conference' => 'Conférence Annuelle des OSC',
    'Public Policy Watch' => 'Surveillance des Politiques Publiques',
    'Community Dialogue' => 'Dialogue Communautaire',
    'ICT4D and Biz Incubation Hub' => 'ICT4D et Biz Incubation Hub',
    'Small Grant Scheme' => 'Programme de Petites Subventions',
    'Meals' => 'Repas',
    'Lodging Facilities' => 'Hébergement',
    'Children Parliament' => 'Parlement des Enfants',
    'Human Resource directory' => 'Répertoire des ressources humaines',
    'The CSO Information and Data Centre (physical/online)' => "Le centre d'information et de données du CSO (physique/en ligne)",
    'Continuous Capacity Building' => 'Renforcement continu des capacités',
    'Strategic networking & twining' => 'Réseautage stratégique et jumelage',
    'Advocacy and lobby for Donor Process streamlining' => 'Plaidoyer et lobby pour la rationalisation du processus des donateurs',
    'Framework for Consultation and dialogue (physical/online)' => 'Cadre de concertation et de dialogue (physique/en ligne)',
    'Establish a very detailed directory of CSO in Cameroon ranked on the basis of an institutional/operational micro assessment conducted on each organization using a mutually agreed assessment tool. The center then works to accompany the CSO to improve their institutional and operational capacities and hence migrate from one category to the other.  The directory is made available online/offline and updated yearly by the Data department of the center' => "Établir un répertoire très détaillé des OSC au Cameroun classées sur la base d'une micro-évaluation institutionnelle/opérationnelle menée sur chaque organisation à l'aide d'un outil d'évaluation convenu d'un commun accord. Le centre travaille alors à accompagner les OSC pour améliorer leurs capacités institutionnelles et opérationnelles et ainsi migrer d'une catégorie à l'autre. L'annuaire est mis à disposition online/offline et mis à jour annuellement par le service Data du centre",
    'A directory of experts in different domains is established and made available online/offline at the center to provide timely and quality technical support to the civil society.  The directory is updated yearly.' => "Un répertoire d'experts dans différents domaines est établi et mis à disposition en ligne/hors ligne au centre pour fournir un soutien technique rapide et de qualité à la société civile. Le répertoire est mis à jour annuellement.",
    'To address the human resource challenges faced by the civil society resulting from high staff turnover and low practical skills among graduates, this service of LACSODEC will focus on a structured professional internship for university graduates aimed at preparing them to the labor pool from where CSO can draw quality human capital. This directory is available offline/online and updated regularly' => "Pour relever les défis en matière de ressources humaines auxquels est confrontée la société civile résultant du roulement élevé du personnel et de la faible compétence pratique des diplômés, ce service de LACSODEC se concentrera sur un stage professionnel structuré pour les diplômés universitaires visant à les préparer au bassin de main-d'œuvre où les OSC peuvent puiser un capital humain de qualité. Ce répertoire est disponible hors ligne/en ligne et mis à jour régulièrement",
    'Accommodate at the center a qualified audit department charged with the development of tools and training modules based on the standard accounting standards (OHADA) and use the same to train and accompany civil society and youth’s startups to establish compliant financial management systems. The department will therefore conduct yearly audits and certify the accounts of participating CSO and thereby increase their eligibility to access resources at national, regional and international levels.' => "Accueillir au centre un département d'audit qualifié chargé du développement d'outils et de modules de formation basés sur les normes comptables standard (OHADA) et l'utiliser pour former et accompagner les startups de la société civile et de la jeunesse à mettre en place des systèmes de gestion financière conformes. Le département effectuera donc des audits annuels et certifiera les comptes des OSC participantes et augmentera ainsi leur admissibilité à accéder aux ressources aux niveaux national, régional et international.",
    'Accommodate a legal advisory department charged with the responsibility to research, analyze, simplify, share and train CSO on available legal frameworks (National, regional and international) guiding their general operations as well as sector-specific reference source documents. The Legal department also has the responsibility to establish a national and regional referral pathway of legal experts to provide timely legal counsel to CSO as well as trigger the network to protect CSO actors in cases of harassment related to their work.' => "Accueillir un service de conseil juridique chargé de rechercher, d'analyser, de simplifier, de partager et de former les OSC sur les cadres juridiques disponibles (nationaux, régionaux et internationaux) guidant leurs opérations générales ainsi que sur les documents sources de référence spécifiques au secteur. Le service juridique a également la responsabilité d'établir une voie de référence nationale et régionale d'experts juridiques pour fournir des conseils juridiques en temps opportun aux OSC ainsi que de déclencher le réseau pour protéger les acteurs des OSC en cas de harcèlement lié à leur travail.",
    'The information and data center (library/archive) will collect and keep resourceful publications good for CSO reference for knowledge and/or consultation during programs/project formulation. The department conducts ongoing assessments, research and publications that are then used to inform local, national, regional and international policy formulation and for evidence-based advocacy for positive change. The center provides secured data backup service that can be used by CSO to prevent data loss that is frequent among CSOs.' => "Le centre d'information et de données (bibliothèque / archives) collectera et conservera des publications ingénieuses bonnes pour la référence des OSC à des fins de connaissance et / ou de consultation lors de la formulation des programmes / projets. Le département mène des évaluations, des recherches et des publications continues qui sont ensuite utilisées pour éclairer la formulation de politiques locales, nationales, régionales et internationales et pour un plaidoyer fondé sur des preuves pour un changement positif. Le centre fournit un service de sauvegarde de données sécurisé qui peut être utilisé par les OSC pour prévenir la perte de données qui est fréquente parmi les OSC.",
    'A key aspect of the LACSODEC is to develop and deliver content and mentorship in specific areas of institutional and operational capacity of the civil society organizations using a hybrid of physical workshops and high technologies such as video conferencing and distant learning. Peer mentorship will be encouraged and supported to allow best practices to be shared across the civil society via placement programs horizontally and vertically across the nation, continent and globally.' => "Un aspect clé du LACSODEC est de développer et de fournir du contenu et du mentorat dans des domaines spécifiques de la capacité institutionnelle et opérationnelle des organisations de la société civile en utilisant un hybride d'ateliers physiques et de hautes technologies telles que la vidéoconférence et l'apprentissage à distance. Le mentorat par les pairs sera encouragé et soutenu pour permettre le partage des meilleures pratiques dans la société civile via des programmes de placement horizontalement et verticalement à travers le pays, le continent et dans le monde.",
    'To meet up with the fast technology world, drawing from the ever-increasing number of youth tech enthusiasts, this department will provide the infrastructure needed to support the development of technologies that respond to the needs of the civil society in particular but also those of businesses, local/national institutions and governments in general. The work of this department will support the digitalization of the LACSODEC as a whole. This service will therefore research, develop and acquire technologies and make these available and accessible to the civil society to improve institutional and operational performance including teleconferencing facilities that can aid holding of meetings and networking remotely and regularly as compared to current cost intensive systems.' => "Pour rencontrer le monde de la technologie rapide, en s'appuyant sur le nombre toujours croissant de jeunes passionnés de technologie, ce département fournira l'infrastructure nécessaire pour soutenir le développement de technologies qui répondent aux besoins de la société civile en particulier mais aussi à ceux des entreprises, des institutions locales/nationales et des gouvernements en général. Les travaux de ce département soutiendront la numérisation de l'ensemble du LACSODEC. Ce service va donc rechercher, développer et acquérir des technologies et les rendre disponibles et accessibles à la société civile pour améliorer les performances institutionnelles et opérationnelles, y compris les installations de téléconférence qui peuvent faciliter la tenue de réunions et la mise en réseau à distance et régulièrement par rapport aux systèmes coûteux actuels.",
    'As a means of promoting and testing acquired knowledge and skills, LUKMEF is introducing the LUKMEF small grant program aimed at providing small grants($1000 - $5000) to small and middle incomes organizations to implement impactful institutional strengthening actions and small human development projects in their respective areas of expertise as a way of validating their institutional and operational capacity toward accessing bigger donor funds.' => "Afin de promouvoir et de tester les connaissances et les compétences acquises, LUKMEF présente le programme de petites subventions LUKMEF visant à fournir de petites subventions (1 000 $ à 5 000 $) aux organisations à revenus petits et moyens pour mettre en œuvre des actions de renforcement institutionnel percutantes et de petits projets de développement humain dans leurs domaines d'expertise respectifs afin de valider leur capacité institutionnelle et opérationnelle à accéder à des fonds de donateurs plus importants.",
    'The center will pay particular attention to the Monitoring, Evaluation and Learning system by developing tools, training modules and delivering same to CSO as well accompanying them towards effective use of tools and collection of qualitative and quantitative data that is used to inform their programs/project formulation and evidence-based advocacy for change.' => "Le centre accordera une attention particulière au système de suivi, d'évaluation et d'apprentissage en développant des outils, des modules de formation et en les livrant aux OSC, ainsi qu'en les accompagnant vers une utilisation efficace des outils et la collecte de données qualitatives et quantitatives qui sont utilisées pour éclairer la formulation de leurs programmes/projets et le plaidoyer fondé sur des preuves pour le changement.",
    'As a strategy to bring visibility and to take its content to beneficiaries in a cost-effective way, the center is designed to harbor a development communication Media center (TV, Radio, Print and online) that has been tested in Buea for the last 3 years to be effective' => "Dans le cadre d'une stratégie visant à apporter de la visibilité et à apporter son contenu aux bénéficiaires de manière rentable, le centre est conçu pour abriter un centre de développement des médias de communication (TV, radio, presse écrite et en ligne) qui a été testé à Buea au cours des 3 dernières années pour être efficace.",
    'Support the yearly organization of a civil society review conference aimed at conducting a global appraisal of the performance of CSO and the operating environment for CSO' => "Soutenir l'organisation annuelle d'une conférence d'examen de la société civile visant à mener une évaluation globale de la performance des OSC et de l'environnement opérationnel des OSC",
    'While LACSODEC is not a network, the center encourages, facilitates and supports north-south and south-south bilateral and multilateral networking, twining and collaboration between CSOs and relevant national and international agencies likely to add value to CSO institutional and operational capacity.' => "Bien que LACSODEC ne soit pas un réseau, le centre encourage, facilite et soutient le réseautage bilatéral et multilatéral nord-sud et sud-sud, le jumelage et la collaboration entre les OSC et les agences nationales et internationales pertinentes susceptibles d'ajouter de la valeur à la capacité institutionnelle et opérationnelle des OSC.",
    'Based on evidence and available accompanying mechanisms, engage with development partners, relevant state agencies and corporate bodies to streamline funding eligibility criteria to accommodate low, middle income and start-up organizations' => "Sur la base des preuves et des mécanismes d'accompagnement disponibles, s'engager avec les partenaires de développement, les agences gouvernementales et les entreprises concernées pour rationaliser les critères d'éligibilité au financement afin d'accueillir les organisations à faible revenu, à revenu intermédiaire et en démarrage",
    'Promote public-private sector dialogue and partnerships for local and national development through a hybrid of physical and technologies to bridge the resource gap that limited such processes in the past.' => 'Promouvoir le dialogue et les partenariats entre les secteurs public et privé pour le développement local et national grâce à un mélange de physique et de technologies pour combler le déficit de ressources qui limitait ces processus dans le passé.',

];
